/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_amarantha_lightboard_board_CLightBoard */

#ifndef _Included_net_amarantha_lightboard_board_CLightBoard
#define _Included_net_amarantha_lightboard_board_CLightBoard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_amarantha_lightboard_board_CLightBoard
 * Method:    initNative
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_amarantha_lightboard_board_CLightBoard_initNative
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     net_amarantha_lightboard_board_CLightBoard
 * Method:    setPoint
 * Signature: (IIZZ)V
 */
JNIEXPORT void JNICALL Java_net_amarantha_lightboard_board_CLightBoard_setPoint
  (JNIEnv *, jobject, jint, jint, jboolean, jboolean);

/*
 * Class:     net_amarantha_lightboard_board_CLightBoard
 * Method:    sleep
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_amarantha_lightboard_board_CLightBoard_sleep
  (JNIEnv *, jobject);

/*
 * Class:     net_amarantha_lightboard_board_CLightBoard
 * Method:    wake
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_amarantha_lightboard_board_CLightBoard_wake
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
