/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_amarantha_lightboard_board_CLightBoard_192x32_Small_Sign */

#ifndef _Included_net_amarantha_lightboard_board_CLightBoard_192x32_Small_Sign
#define _Included_net_amarantha_lightboard_board_CLightBoard_192x32_Small_Sign
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_amarantha_lightboard_board_CLightBoard_192x32_Small_Sign
 * Method:    initNative
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_amarantha_lightboard_board_CLightBoard_1192x32_1Small_1Sign_initNative
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     net_amarantha_lightboard_board_CLightBoard_192x32_Small_Sign
 * Method:    setPoint
 * Signature: (IIZZ)V
 */
JNIEXPORT void JNICALL Java_net_amarantha_lightboard_board_CLightBoard_1192x32_1Small_1Sign_setPoint
  (JNIEnv *, jobject, jint, jint, jboolean, jboolean);

/*
 * Class:     net_amarantha_lightboard_board_CLightBoard_192x32_Small_Sign
 * Method:    sleep
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_amarantha_lightboard_board_CLightBoard_1192x32_1Small_1Sign_sleep
  (JNIEnv *, jobject);

/*
 * Class:     net_amarantha_lightboard_board_CLightBoard_192x32_Small_Sign
 * Method:    wake
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_amarantha_lightboard_board_CLightBoard_1192x32_1Small_1Sign_wake
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
