/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_amarantha_lightboard_board_impl_CLightBoard */

#ifndef _Included_net_amarantha_lightboard_board_impl_CLightBoard
#define _Included_net_amarantha_lightboard_board_impl_CLightBoard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_amarantha_lightboard_board_impl_CLightBoard
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_amarantha_lightboard_board_impl_CLightBoard_init
  (JNIEnv *, jobject);

/*
 * Class:     net_amarantha_lightboard_board_impl_CLightBoard
 * Method:    dump
 * Signature: ([[[D)V
 */
JNIEXPORT void JNICALL Java_net_amarantha_lightboard_board_impl_CLightBoard_dump
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
